const ProductsActionsTypes = {
  ADD_PRODUCT_START: "ADD_PRODUCT_START",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  ADD_PRODUCT_RESTART: "ADD_PRODUCT_RESTART",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",
  DELETE_PRODUCT_RESTART: "DELETE_PRODUCT_RESTART",
  UPDATE_PRODUCT_START: "UPDATE_PRODUCT_START",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
  UPDATE_PRODUCT_RESTART: "UPDATE_PRODUCT_RESTART",
  RETRIEVE_PRODUCTS_START: "RETRIEVE_PRODUCTS_START",
  RETRIEVE_PRODUCTS_SUCCESS: "RETRIEVE_PRODUCTS_SUCCESS",
  RETRIEVE_PRODUCTS_FAILURE: "RETRIEVE_PRODUCTS_FAILURE",
  UPDATE_QUANTITY_START: "UPDATE_QUANTITY_START",
  UPDATE_QUANTITY_SUCCESS: "UPDATE_QUANTITY_SUCCESS",
  UPDATE_QUANTITY_FAILURE: "UPDATE_QUANTITY_FAILURE",
};

export default ProductsActionsTypes;
