const StockInsActionsTypes = {
  ADD_STOCK_IN_START: "ADD_STOCK_IN_START",
  ADD_STOCK_IN_SUCCESS: "ADD_STOCK_IN_SUCCESS",
  ADD_STOCK_IN_FAILURE: "ADD_STOCK_IN_FAILURE",
  ADD_STOCK_IN_RESTART: "ADD_STOCK_IN_RESTART",
  DELETE_STOCK_IN_START: "DELETE_STOCK_IN_START",
  DELETE_STOCK_IN_SUCCESS: "DELETE_STOCK_IN_SUCCESS",
  DELETE_STOCK_IN_FAILURE: "DELETE_STOCK_IN_FAILURE",
  DELETE_STOCK_IN_RESTART: "DELETE_STOCK_IN_RESTART",
  UPDATE_STOCK_IN_START: "UPDATE_STOCK_IN_START",
  UPDATE_STOCK_IN_SUCCESS: "UPDATE_STOCK_IN_SUCCESS",
  UPDATE_STOCK_IN_FAILURE: "UPDATE_STOCK_IN_FAILURE",
  UPDATE_STOCK_IN_RESTART: "UPDATE_STOCK_IN_RESTART",
  RETRIEVE_STOCK_INS_START: "RETRIEVE_STOCK_INS_START",
  RETRIEVE_STOCK_INS_SUCCESS: "RETRIEVE_STOCK_INS_SUCCESS",
  RETRIEVE_STOCK_INS_FAILURE: "RETRIEVE_STOCK_INS_FAILURE",
};

export default StockInsActionsTypes;
