const UserActionTypes = {
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  RESTART_USER_REDUCER_START: "RESTART_USER_REDUCER_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  USER_RESTART: "USER_RESTART",
};

export default UserActionTypes;
