const StockOutsActionsTypes = {
  ADD_STOCK_OUT_START: "ADD_STOCK_OUT_START",
  ADD_STOCK_OUT_SUCCESS: "ADD_STOCK_OUT_SUCCESS",
  ADD_STOCK_OUT_FAILURE: "ADD_STOCK_OUT_FAILURE",
  ADD_STOCK_OUT_RESTART: "ADD_STOCK_OUT_RESTART",
  DELETE_STOCK_OUT_START: "DELETE_STOCK_OUT_START",
  DELETE_STOCK_OUT_SUCCESS: "DELETE_STOCK_OUT_SUCCESS",
  DELETE_STOCK_OUT_FAILURE: "DELETE_STOCK_OUT_FAILURE",
  DELETE_STOCK_OUT_RESTART: "DELETE_STOCK_OUT_RESTART",
  UPDATE_STOCK_OUT_START: "UPDATE_STOCK_OUT_START",
  UPDATE_STOCK_OUT_SUCCESS: "UPDATE_STOCK_OUT_SUCCESS",
  UPDATE_STOCK_OUT_FAILURE: "UPDATE_STOCK_OUT_FAILURE",
  UPDATE_STOCK_OUT_RESTART: "UPDATE_STOCK_OUT_RESTART",
  RETRIEVE_STOCK_OUTS_START: "RETRIEVE_STOCK_OUTS_START",
  RETRIEVE_STOCK_OUTS_SUCCESS: "RETRIEVE_STOCK_OUTS_SUCCESS",
  RETRIEVE_STOCK_OUTS_FAILURE: "RETRIEVE_STOCK_OUTS_FAILURE",
};

export default StockOutsActionsTypes;
